services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: invoiceks
      POSTGRES_USER: invoiceks
      POSTGRES_PASSWORD: invoiceks
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.keystone/postgres:/var/lib/postgresql/data
